before_install:
  # Couchbase Server
  - sudo wget http://packages.couchbase.com/releases/2.0.0/couchbase-server-enterprise_x86_64_2.0.0.deb
  - sudo dpkg -i couchbase-server-enterprise_x86_64_2.0.0.deb
  - sudo service couchbase-server start
  - /opt/couchbase/bin/couchbase-cli cluster-init -c 127.0.0.1:8091 --cluster-init-username=Administrator --cluster-init-password=password --cluster-init-ramsize=256
  - /opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=default --bucket-type=couchbase --bucket-port=11211 --bucket-ramsize=100 --bucket-replica=0 -u Administrator -p password
notifications:
  email:
    - mike@urlgonomics.com
language: ruby
rvm:
  - jruby-19mode
